version: '3.6'
services:
  money-transfer.api:
    image: digma/sample.money-transfer:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - Digma__URL=http://digma-collector-api:5050
      - DEPLOYMENT_COMMIT_ID
      - DEPLOYMENT_ENV
      - DIGMA_ENV_TYPE
    ports:
      - "7151:7151"
    networks:
      - digma-network
networks:
  digma-network:
    external: true